"""Add created_at to InviteCode

Revision ID: 5e30e0c904e6
Revises: b4bfad26f602
Create Date: 2025-08-30 10:30:47.159910

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5e30e0c904e6'
down_revision = 'b4bfad26f602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invite_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('used_at', sa.DateTime(), nullable=True))
        batch_op.alter_column(
            'code',
            existing_type=sa.VARCHAR(length=32),
            type_=sa.String(length=20),
            nullable=False
        )
        batch_op.create_foreign_key(
            'fk_invite_code_created_by_user',  # must match in downgrade
            'user',
            ['created_by'],
            ['id']
        )

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('active')

    with op.batch_alter_table('invite_code', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_invite_code_created_by_user',  # same name as above
            type_='foreignkey'
        )
        batch_op.alter_column(
            'code',
            existing_type=sa.String(length=20),
            type_=sa.VARCHAR(length=32),
            nullable=True
        )
        batch_op.drop_column('used_at')
        batch_op.drop_column('created_by')
    # ### end Alembic commands ###