"""Update user model with status and financial status

Revision ID: 76066b631c19
Revises: 180f39404fce
Create Date: 2025-08-21 12:23:08.274008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76066b631c19'
down_revision = '180f39404fce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('financial_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('financial_status')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
