"""add active field to user

Revision ID: 764d7ead9ca1
Revises: 1416718e9d54
Create Date: 2025-09-04 11:26:08.709353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764d7ead9ca1'
down_revision = '1416718e9d54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
