"""Adds plan_id relationship to Payment

Revision ID: 7775ad9a6959
Revises: d575eecbc636
Create Date: 2025-08-19 12:54:52.370128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7775ad9a6959'
down_revision = 'd575eecbc636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_payment_plan_id', 'payment_plan', ['plan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payment_plan_id', type_='foreignkey')
        batch_op.drop_column('plan_id')

    # ### end Alembic commands ###
