"""add enforce_installements to PaymentPlan

Revision ID: 87716b91f3db
Revises: 7f82ea226464
Create Date: 2025-09-07 13:08:33.060704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87716b91f3db'
down_revision = '7f82ea226464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_plan', sa.Column('enforce_installments', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_plan', 'enforce_installments')
    # ### end Alembic commands ###
