"""Add initiation_date to User

Revision ID: 8a5a34d89c28
Revises: 87716b91f3db
Create Date: 2025-10-04 17:20:58.743285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a5a34d89c28'
down_revision = '87716b91f3db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('initiation_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'initiation_date')
    # ### end Alembic commands ###
