"""Add Donation model and update WebhookEvent with source field

Revision ID: 9dc18b4119ee
Revises: 521146e52b5e
Create Date: 2025-11-09 19:20:26.351171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dc18b4119ee'
down_revision = '521146e52b5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip creating views - they already exist and should be managed separately
    # op.create_table('dues_paid_view', ...)
    # op.create_table('payment_plan_stats_view', ...)

    op.create_table('donation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_name', sa.String(length=100), nullable=False),
    sa.Column('donor_email', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('stripe_payment_id', sa.String(length=128), nullable=True),
    sa.Column('anonymous', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_payment_id')
    )
    op.create_index(op.f('ix_donation_date'), 'donation', ['date'], unique=False)
    op.drop_index(op.f('ix_invite_code_code'), table_name='invite_code')
    op.drop_index(op.f('ix_invite_code_expires_at'), table_name='invite_code')
    op.drop_index(op.f('ix_invite_code_used'), table_name='invite_code')
    op.drop_index(op.f('ix_payment_date'), table_name='payment')
    op.drop_index(op.f('ix_payment_method'), table_name='payment')
    op.drop_index(op.f('ix_payment_plan_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_type'), table_name='payment')
    op.drop_index(op.f('ix_payment_user_id_date'), table_name='payment')
    op.drop_index(op.f('ix_payment_plan_end_date'), table_name='payment_plan')
    op.drop_index(op.f('ix_payment_plan_start_date'), table_name='payment_plan')
    op.drop_index(op.f('ix_payment_plan_status'), table_name='payment_plan')
    op.drop_index(op.f('ix_payment_plan_user_status'), table_name='payment_plan')
    op.drop_index(op.f('ix_user_active'), table_name='user')
    op.drop_index(op.f('ix_user_financial_status'), table_name='user')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.add_column('webhook_event', sa.Column('source', sa.String(length=20), nullable=True))
    op.drop_index(op.f('ix_webhook_event_type'), table_name='webhook_event')
    op.drop_index(op.f('ix_webhook_processed'), table_name='webhook_event')
    op.drop_index(op.f('ix_webhook_received_at'), table_name='webhook_event')
    op.create_index(op.f('ix_webhook_event_event_type'), 'webhook_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_event_processed'), 'webhook_event', ['processed'], unique=False)
    op.create_index(op.f('ix_webhook_event_received_at'), 'webhook_event', ['received_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_event_received_at'), table_name='webhook_event')
    op.drop_index(op.f('ix_webhook_event_processed'), table_name='webhook_event')
    op.drop_index(op.f('ix_webhook_event_event_type'), table_name='webhook_event')
    op.create_index(op.f('ix_webhook_received_at'), 'webhook_event', ['received_at'], unique=False)
    op.create_index(op.f('ix_webhook_processed'), 'webhook_event', ['processed'], unique=False)
    op.create_index(op.f('ix_webhook_event_type'), 'webhook_event', ['event_type'], unique=False)
    op.drop_column('webhook_event', 'source')
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_index(op.f('ix_user_financial_status'), 'user', ['financial_status'], unique=False)
    op.create_index(op.f('ix_user_active'), 'user', ['active'], unique=False)
    op.create_index(op.f('ix_payment_plan_user_status'), 'payment_plan', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_payment_plan_status'), 'payment_plan', ['status'], unique=False)
    op.create_index(op.f('ix_payment_plan_start_date'), 'payment_plan', ['start_date'], unique=False)
    op.create_index(op.f('ix_payment_plan_end_date'), 'payment_plan', ['end_date'], unique=False)
    op.create_index(op.f('ix_payment_user_id_date'), 'payment', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_payment_type'), 'payment', ['payment_type'], unique=False)
    op.create_index(op.f('ix_payment_plan_id'), 'payment', ['plan_id'], unique=False)
    op.create_index(op.f('ix_payment_method'), 'payment', ['method'], unique=False)
    op.create_index(op.f('ix_payment_date'), 'payment', ['date'], unique=False)
    op.create_index(op.f('ix_invite_code_used'), 'invite_code', ['used'], unique=False)
    op.create_index(op.f('ix_invite_code_expires_at'), 'invite_code', ['expires_at'], unique=False)
    op.create_index(op.f('ix_invite_code_code'), 'invite_code', ['code'], unique=False)
    op.drop_index(op.f('ix_donation_date'), table_name='donation')
    op.drop_table('donation')
    # Skip dropping views - they should be managed separately
    # op.drop_table('payment_plan_stats_view')
    # op.drop_table('dues_paid_view')
    # ### end Alembic commands ###
