"""Add EmailEvent table for SendGrid webhook tracking

Revision ID: a1b2c3d4e5f6
Revises: 9dc18b4119ee
Create Date: 2026-01-16 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '9dc18b4119ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('smtp_id', sa.String(length=255), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index(op.f('ix_email_event_email'), 'email_event', ['email'], unique=False)
    op.create_index(op.f('ix_email_event_event_id'), 'email_event', ['event_id'], unique=True)
    op.create_index(op.f('ix_email_event_event_type'), 'email_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_email_event_timestamp'), 'email_event', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_event_timestamp'), table_name='email_event')
    op.drop_index(op.f('ix_email_event_event_type'), table_name='email_event')
    op.drop_index(op.f('ix_email_event_event_id'), table_name='email_event')
    op.drop_index(op.f('ix_email_event_email'), table_name='email_event')
    op.drop_table('email_event')
    # ### end Alembic commands ###
