"""made updates to the invite database model

Revision ID: b4bfad26f602
Revises: 431886986791
Create Date: 2025-08-27 11:50:03.695597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b4bfad26f602'
down_revision = '431886986791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invite_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('used_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.create_foreign_key(None, 'user', ['created_by'], ['id'])
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invite_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.drop_column('used_at')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
