"""Rename type to payment_typein the Payment model

Revision ID: d575eecbc636
Revises: b24ab0f9bbbe
Create Date: 2025-08-19 12:44:11.402805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd575eecbc636'
down_revision = 'b24ab0f9bbbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_type', sa.String(length=20), nullable=True))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('payment_type')

    # ### end Alembic commands ###
